import type { Category, ReporterProfile, Report, VisionEchoDb } from "./types";

const now = new Date("2026-05-06T12:00:00.000Z");

function minutesAgo(minutes: number) {
  return new Date(now.getTime() - minutes * 60_000).toISOString();
}

export const categories: Category[] = [
  {
    id: "cat-elections",
    name: "Elections",
    slug: "elections",
    icon: "Landmark",
    active: true,
    summary: "Polling unit updates, voter access, collation observations, and campaign accountability.",
  },
  {
    id: "cat-governance",
    name: "Governance",
    slug: "governance",
    icon: "Building2",
    active: true,
    summary: "Public policy, budgets, appointments, service delivery, and official civic notices.",
  },
  {
    id: "cat-security",
    name: "Security",
    slug: "security",
    icon: "ShieldAlert",
    active: true,
    summary: "Safety alerts, emergency response, public order, and community protection reports.",
  },
  {
    id: "cat-infrastructure",
    name: "Infrastructure",
    slug: "infrastructure",
    icon: "Construction",
    active: true,
    summary: "Roads, power, water, transport, public works, and maintenance tracking.",
  },
  {
    id: "cat-economy",
    name: "Economy",
    slug: "economy",
    icon: "LineChart",
    active: true,
    summary: "Markets, labour, prices, public revenue, small business, and consumer impact.",
  },
  {
    id: "cat-community",
    name: "Community",
    slug: "community",
    icon: "HeartHandshake",
    active: true,
    summary: "Local action, civic meetings, public health, education, and neighbourhood voices.",
  },
];

export const reporters: ReporterProfile[] = [
  {
    id: "r-ada",
    name: "Ada Nwosu",
    initials: "AN",
    beat: "Elections and governance",
    base: "Abuja FCT",
    bio: "Field reporter covering voter access, civic institutions, and public finance.",
    verifiedStories: 42,
    totalStories: 118,
    trustScore: 98,
    status: "verified",
  },
  {
    id: "r-tunde",
    name: "Tunde Bakare",
    initials: "TB",
    beat: "Infrastructure and transport",
    base: "Lagos",
    bio: "Reporter tracking public works, mobility, roads, and urban services.",
    verifiedStories: 37,
    totalStories: 96,
    trustScore: 96,
    status: "verified",
  },
  {
    id: "r-zainab",
    name: "Zainab Musa",
    initials: "ZM",
    beat: "Security and community resilience",
    base: "Kano",
    bio: "Community-focused reporter covering safety, education, and local response.",
    verifiedStories: 29,
    totalStories: 77,
    trustScore: 94,
    status: "verified",
  },
];

export const reports: Report[] = [
  {
    id: "ve-1001",
    title: "Polling unit queue moving after late accreditation device replacement",
    slug: "polling-unit-queue-moving-after-device-replacement",
    categorySlug: "elections",
    locationName: "Garki, Abuja FCT",
    state: "FCT",
    latitude: 9.036,
    longitude: 7.489,
    body: "Voters say the first accreditation device failed before noon. INEC officials replaced it and voting resumed with party agents present at the unit.",
    sourceType: "Reporter",
    authorName: "Ada Nwosu",
    reporterId: "r-ada",
    status: "verified",
    live: true,
    priority: "breaking",
    media: [
      {
        id: "m-1001",
        type: "image",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Area_shot_of_polling_units.jpg/960px-Area_shot_of_polling_units.jpg",
        status: "approved",
      },
    ],
    evidence: [
      { id: "e-1001-a", label: "Video clip reviewed", type: "media", confidence: 86 },
      { id: "e-1001-b", label: "Location matched", type: "location", confidence: 92 },
      { id: "e-1001-c", label: "Official presence confirmed", type: "source", confidence: 82 },
    ],
    comments: [
      {
        id: "c-1001-a",
        reportId: "ve-1001",
        name: "Chika",
        text: "Can confirm the queue started moving again.",
        status: "visible",
        createdAt: minutesAgo(8),
      },
    ],
    reviewTrail: [
      {
        id: "rd-1001",
        reportId: "ve-1001",
        editorName: "Editor Desk",
        decision: "approved",
        reason: "Multiple source checks passed.",
        createdAt: minutesAgo(10),
      },
    ],
    createdAt: minutesAgo(12),
    updatedAt: minutesAgo(10),
  },
  {
    id: "ve-1002",
    title: "Commuters report flooding near Mile 12 market access road",
    slug: "commuters-report-flooding-near-mile-12-market-access-road",
    categorySlug: "infrastructure",
    locationName: "Mile 12, Lagos",
    state: "Lagos",
    latitude: 6.605,
    longitude: 3.398,
    body: "Eyewitness footage shows traffic slowing around the market corridor after heavy rainfall. Road users are asking LASTMA for diversion support.",
    sourceType: "Reporter",
    authorName: "Tunde Bakare",
    reporterId: "r-tunde",
    status: "in_review",
    live: true,
    priority: "high",
    media: [
      {
        id: "m-1002",
        type: "image",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Aerial_view_of_a_busy_tomato_market_in_Lagos_Nigeria.jpg/960px-Aerial_view_of_a_busy_tomato_market_in_Lagos_Nigeria.jpg",
        status: "approved",
      },
    ],
    evidence: [
      { id: "e-1002-a", label: "Image uploaded", type: "media", confidence: 70 },
      { id: "e-1002-b", label: "Two eyewitnesses", type: "source", confidence: 64 },
      { id: "e-1002-c", label: "Weather report pending", type: "document", confidence: 45 },
    ],
    comments: [],
    reviewTrail: [],
    createdAt: minutesAgo(24),
    updatedAt: minutesAgo(24),
  },
  {
    id: "ve-1003",
    title: "Market leaders announce new waste collection schedule",
    slug: "market-leaders-announce-new-waste-collection-schedule",
    categorySlug: "governance",
    locationName: "Idumota, Lagos",
    state: "Lagos",
    body: "A traders association notice reviewed by VisionEcho says waste pickup will run before 7am on Mondays, Wednesdays, and Saturdays.",
    sourceType: "Eyewitness",
    authorName: "Kemi A.",
    status: "verified",
    live: false,
    priority: "normal",
    media: [
      {
        id: "m-1003",
        type: "image",
        url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Ever-busy_market.jpg/960px-Ever-busy_market.jpg",
        status: "approved",
      },
    ],
    evidence: [
      { id: "e-1003-a", label: "Document photo", type: "document", confidence: 84 },
      { id: "e-1003-b", label: "Association contact", type: "source", confidence: 80 },
      { id: "e-1003-c", label: "Editor call-back", type: "editor", confidence: 88 },
    ],
    comments: [
      {
        id: "c-1003-a",
        reportId: "ve-1003",
        name: "Bayo",
        text: "This will help if enforcement is consistent.",
        status: "visible",
        createdAt: minutesAgo(18),
      },
    ],
    reviewTrail: [
      {
        id: "rd-1003",
        reportId: "ve-1003",
        editorName: "Editor Desk",
        decision: "approved",
        createdAt: minutesAgo(52),
      },
    ],
    createdAt: minutesAgo(58),
    updatedAt: minutesAgo(52),
  },
  {
    id: "ve-1004",
    title: "Community volunteers reopen evening study centre",
    slug: "community-volunteers-reopen-evening-study-centre",
    categorySlug: "community",
    locationName: "Sabon Gari, Kano",
    state: "Kano",
    body: "Teachers and residents reopened a donated classroom for secondary school exam prep after a two-month closure caused by roof repairs.",
    sourceType: "Reporter",
    authorName: "Zainab Musa",
    reporterId: "r-zainab",
    status: "verified",
    live: false,
    priority: "normal",
    media: [],
    evidence: [
      { id: "e-1004-a", label: "Reporter visit", type: "editor", confidence: 90 },
      { id: "e-1004-b", label: "Volunteer interview", type: "source", confidence: 78 },
      { id: "e-1004-c", label: "Photo pending", type: "media", confidence: 38 },
    ],
    comments: [],
    reviewTrail: [],
    createdAt: minutesAgo(90),
    updatedAt: minutesAgo(90),
  },
  {
    id: "ve-1005",
    title: "Fuel queue forming around two stations after supply delay",
    slug: "fuel-queue-forming-around-two-stations-after-supply-delay",
    categorySlug: "economy",
    locationName: "Port Harcourt, Rivers",
    state: "Rivers",
    body: "Drivers report a growing queue around two filling stations. A station attendant said a tanker delivery is expected later this evening.",
    sourceType: "Eyewitness",
    authorName: "Eyewitness 204",
    status: "in_review",
    live: true,
    priority: "high",
    media: [{ id: "m-1005", type: "audio", url: "", status: "uploaded" }],
    evidence: [
      { id: "e-1005-a", label: "Audio note", type: "media", confidence: 60 },
      { id: "e-1005-b", label: "Location submitted", type: "location", confidence: 74 },
      { id: "e-1005-c", label: "Awaiting second source", type: "source", confidence: 35 },
    ],
    comments: [],
    reviewTrail: [],
    createdAt: minutesAgo(5),
    updatedAt: minutesAgo(5),
  },
];

export const seedDb: VisionEchoDb = {
  categories,
  reporters,
  reports,
};
